sonar.projectKey=nd170504-coder_PRM393_VNMAP
sonar.organization=nd170504-coder

sonar.sources=lib
sonar.tests=test

# Flutter coverage
sonar.dart.lcov.reportPaths=coverage/lcov.info

# Exclude generated files
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated/**