import 'package:flutter/material.dart';
import '../models/household_model.dart';
import '../models/household_request_model.dart';
import '../services/database_service.dart';

class HouseholdRequestProvider extends ChangeNotifier {
  final DatabaseService _db;

  HouseholdRequestProvider({DatabaseService? db})
    : _db = db ?? DatabaseService();
  List<HouseholdRequest> _requests = [];
  bool _isLoading = false;
  String? _error;

  List<HouseholdRequest> get requests => _requests;
  bool get isLoading => _isLoading;
  String? get error => _error;

  List<HouseholdRequest> get pendingRequests =>
      _requests.where((r) => r.status == 'pending').toList();

  List<HouseholdRequest> get approvedRequests =>
      _requests.where((r) => r.status == 'approved').toList();

  List<HouseholdRequest> get rejectedRequests =>
      _requests.where((r) => r.status == 'rejected').toList();

  @visibleForTesting
  void setRequestsForTesting(List<HouseholdRequest> requests) {
    _requests = requests;
  }

  Future<void> fetchAllRequests() async {
    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      _requests = await _db.fetchHouseholdRequests();
    } catch (e) {
      _error = e.toString();
    }

    _isLoading = false;
    notifyListeners();
  }

  Future<List<HouseholdRequest>> fetchUserRequests(int userId) async {
    try {
      return await _db.fetchHouseholdRequests(userId: userId);
    } catch (e) {
      _error = e.toString();
      return [];
    }
  }

  Future<HouseholdRequest?> getUserPendingRequest(int userId) async {
    try {
      final requests = await _db.fetchHouseholdRequests(
        userId: userId,
        status: 'pending',
      );
      return requests.isNotEmpty ? requests.first : null;
    } catch (e) {
      return null;
    }
  }

  Future<bool> createRequest(HouseholdRequest request) async {
    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      await _db.createHouseholdRequest(request);
      _isLoading = false;
      notifyListeners();
      return true;
    } catch (e) {
      _error = e.toString();
      _isLoading = false;
      notifyListeners();
      return false;
    }
  }

  Future<void> loadRequests({String? status, int? userId}) async {
    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      _requests = await _db.fetchHouseholdRequests(
        status: status,
        userId: userId,
      );
    } catch (e) {
      _error = e.toString();
    }

    _isLoading = false;
    notifyListeners();
  }

  Future<bool> approveRequest(
    int requestId, {
    required int approvedBy,
    String? adminNote,
  }) async {
    _error = null;
    try {
      // 1. Fetch request details
      final request = await _db.fetchHouseholdRequestById(requestId);
      if (request == null) {
        _error = 'Không tìm thấy yêu cầu';
        notifyListeners();
        return false;
      }

      // 2. Update request status to approved
      await _db.updateHouseholdRequestStatus(
        requestId,
        'approved',
        approvedBy: approvedBy,
        adminNote: adminNote,
      );

      // 3. Create actual household record from request data
      final household = Household(
        householdCode: '', // will be auto-generated by createHousehold
        headOfHousehold: request.headOfHousehold,
        houseNumber: request.houseNumber,
        street: request.street,
        neighborhood: request.neighborhood,
        ward: request.ward,
        district: request.district,
        city: request.city,
        phone: request.phone,
        email: request.email,
        population: request.population,
        notes: request.notes,
        createdBy: request.userId,
      );
      await _db.createHousehold(household);

      await loadRequests();
      return true;
    } catch (e) {
      _error = e.toString();
      notifyListeners();
      return false;
    }
  }

  Future<bool> rejectRequest(
    int requestId, {
    required int approvedBy,
    String? adminNote,
  }) async {
    _error = null;
    try {
      await _db.updateHouseholdRequestStatus(
        requestId,
        'rejected',
        approvedBy: approvedBy,
        adminNote: adminNote,
      );
      await loadRequests();
      return true;
    } catch (e) {
      _error = e.toString();
      notifyListeners();
      return false;
    }
  }
}
